[로또] 이인협 미션 제출합니다.
gdgoc-skhu-missions/kotlin-lotto pull request #1
Opened 2024-05-13 09:03 UTC by cucumber99

## 어려웠던 점
- Controller에서 연결할 때 코드가 많이 꼬인 것 같습니다. 또한 모델에서 뷰로 데이터를 전달할 때 getter를 노출한 부분이 있는데 이 부분은 추후 리팩토링을 진행할 때 DTO 등 다른 방법을 이용하여 수정하려고 합니다.
- 이번 미션에서 의존성 주입을 많이 이용해 보았는데, 이러한 방식이 효율성 높은 방식인지 궁금합니다.

2024-05-18 17:21 UTC, hangillee requested changes
안녕하세요, 인협! 👋
중간고사 끝나고 미션 하느라 고생 많으셨습니다!

Q.
**이번 미션에서 의존성 주입을 많이 이용해 보았는데, 이러한 방식이 효율성 높은 방식인지 궁금합니다.**

A.
의존성 주입을 많이 사용하면 효율성이 높아진다라는 생각보단 **모든 객체는 추상화에 의존하고 그 구현 객체를 외부에서 주입하는 것이 좀 더 객체지향스럽다**가 더 올바른 관점일 것 같습니다. 이는 DIP(의존관계 역전 원칙)와도 깊은 연관이 있습니다. 의존성 주입은 IoC(제어의 역전)의 한 방식일 뿐이며, 코드의 효율성이나 성능을 높여주는 것과는 관계가 없습니다. (추상화에만 의존하고 구현 객체를 외부에서 주입하게 하면 내부 구현을 직접 읽어가며 알아야 하는 수고는 덜 수 있으니 완전 관계 없진 않을 수도 있습니다.)

DTO 활용 이유에 대해서 잘 알고 있는 것 같습니다. 리팩토링 파이팅!

2024-05-18 17:21 UTC, hangillee commented on docs/README.md
> +- 도메인 로직에 단위 테스트를 구현해야한다.
기능 구현 목록 작성 👍

2024-05-18 17:21 UTC, hangillee commented on src/main/kotlin/lotto/controller/Controller.kt
> +    }
요구 사항에도 있지만, 이번 미션에서 메소드 indent(들여쓰기)는 1단계까지만 허용하고 있습니다.
메소드 분리 등의 방법을 활용해서 들여쓰기 단계를 낮춰봅시다.

2024-05-18 17:21 UTC, hangillee commented on src/main/kotlin/lotto/controller/Controller.kt
> +    private fun generateLottoTickets(purchaseAmount: Int): List<List<Int>> {
`List<List<Int>>`라는 반환형은 정확히 어떤 값을 반환하고 있는지 이해하기 힘든 것 같습니다.
`Tickets`라는 훌륭한 일급 컬렉션을 구현했음에도 활용하지 않은 이유가 있나요?

2024-05-18 17:21 UTC, hangillee commented on src/main/kotlin/lotto/model/Prize.kt
> +}
`enum class` 대신 `companion object`를 활용하신 이유가 무엇인가요?

2024-05-18 17:21 UTC, hangillee commented on src/main/kotlin/lotto/model/Rank.kt
> +    }
`early return` 👍

2024-05-18 17:21 UTC, hangillee commented on src/main/kotlin/lotto/model/Tickets.kt
> +    }
일급 컬렉션의 내부 상태가 변경되는 현재의 구현 방법과 새 티켓을 가지는 `Tickets`를 반환하는 것 중,
인협은 어느 쪽이 더 객체지향, 클린 코드에 가깝다고 생각하시나요?

2024-05-18 17:21 UTC, hangillee commented on src/main/kotlin/lotto/util/Validator.kt
> +object Validator {
`object`와 `class`의 차이는 무엇인가요?

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/BonusTest.kt
> +        }
`AssertJ`의 `assertThatThrownBy`를 활용해보는 것도 추천드립니다!

`AssertJ`와 `JUnit5 Assertion`은 혼용하기도 하고 개발자의 취향에 따라 호불호가 갈립니다.
다만, 제가 `AssertJ`도 학습해볼 것을 추천드리는 이유는 가독성 및 더 상세한 테스트 실패 이유를 알려주기 때문입니다.

리팩토링은 인협의 선택입니다! 😁

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/BonusTest.kt
> +    }
예외 상황에 대한 테스트 👍

해피 케이스에 대해서 테스트하는 것보단 예외 상황에 대한 테스트와 경계값 테스트가 더 중요합니다!
우리가 테스트를 작성하는 이유가 결국 우리의 코드를 신뢰하기 위해서임을 생각하면 당연할지도..?

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/LottoTest.kt
> +    fun should_ThrowException_When_Duplicate() {
`@DisplayName` 활용 👍

한글 메소드 이름은 매우 낮은 확률이지만 한글 지원 인코딩이 존재하지 않는 환경에서 깨질 수 있습니다!

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/PrizeTest.kt
> +    fun when_Given_Rank_Then_ReturnCorrectPrizeMoney() {
메소드 이름에 스네이크 케이스와 카멜 케이스를 혼용한 이유가 있나요?

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/LottoTest.kt
>      }
경계값 테스트 👍

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/LottoTest.kt
>  class LottoTest {
예외 상황에 대한 여러 테스트를 잘 작성해주셨군요!

다만, 해피 케이스에 대한 테스트도 추가로 작성되면 더 좋을 것 같습니다!

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/PurchaseTest.kt
> +    fun given_Amount_When_CalculatingPurchaseCount_Then_ResultEqualsExpectedPurchaseCount() {
테스트 메소드의 이름이 `@DisplayName`에서 알리는 내용과 꼭 같을 필요는 없습니다! 😁

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/RankingTest.kt
> +class RankingTest {
이 테스트 코드는 정상적으로 동작하지 않네요..
미션 제출 전, 모든 테스트가 정상 통과했는지 확인해주세요!

<img width="529" alt="스크린샷 2024-05-19 오전 2 11 34" src="https://github.com/gdsc-skhu-pair-mission/kotlin-lotto/assets/14046092/1b892883-be3d-4817-862b-98e6ad173bbc">

2024-05-18 17:21 UTC, hangillee commented on src/test/kotlin/lotto/TicketsTest.kt
> +    }
`LottoTest`에서 이미 테스트 된 기능을 다시 한 번 검증한 이유는 무엇인가요? (단순 궁금증입니다. 리팩토링 할 필요는 없어요.)

2024-05-20 03:04 UTC, cucumber99 commented on src/main/kotlin/lotto/controller/Controller.kt
> +    private fun generateLottoTickets(purchaseAmount: Int): List<List<Int>> {
처음에는 Tickets 객체를 반환하는 방식으로 코드를 작성했었는데, View에 데이터를 전달할 때 DTO를 사용하지 않고는 getter가 노출되지 때문에 위와 같이 코드를 수정했었습니다. 객체를 반환하고 DTO를 사용하는 방식으로 수정해보겠습니다.

2024-05-20 03:29 UTC, cucumber99 commented on src/main/kotlin/lotto/model/Prize.kt
> +}
위의 상수들은 해당 클래스 내부에서만 사용되기 때문에 `enum class`를 통해 상수 집합을 관리하기 보다는 `companion object` 내부에 상수를 작성하는 간단한 방법을 선택했습니다. `enum class`를 사용하는 방법도 한 번 생각해 보겠습니다.

2024-05-20 03:31 UTC, hangillee commented on src/main/kotlin/lotto/model/Prize.kt
> +}
단순 궁금증이었습니다! 리팩토링은 하지 않아도 됩니다ㅋㅋ

2024-05-20 03:34 UTC, cucumber99 commented on src/test/kotlin/lotto/PrizeTest.kt
> +    fun when_Given_Rank_Then_ReturnCorrectPrizeMoney() {
처음에는 모두 카멜 케이스로 작성했는데, IDE에서 경고문이 발생해서 별 생각없이 수정했습니다..
제대로 고쳐보도록 하겠습니다.

2024-05-20 03:37 UTC, cucumber99 commented on src/test/kotlin/lotto/TicketsTest.kt
> +    }
`LottoTest`에서 로또 번호 범위에 대한 테스트 코드는 사용자가 입력한 당첨 번호에 해당하고, 위의 테스트 코드는 `pickUniqueNumberInRange()`에 의해 무작위로 생성된 로또 번호들입니다. 같은 로또 번호이지만 엄연히 다른 동작에 의해 생성된 번호이기 때문에 각자 테스트가 필요하다고 생각했습니다.

2024-05-20 03:39 UTC, cucumber99 commented on src/main/kotlin/lotto/util/Validator.kt
> +object Validator {
제가 생각하는 큰 차이는 생성자의 유무와 싱글톤 여부입니다. `Validator`나 `View`는 `object`로 다루는 것이 더 적합할 것이라고 생각하였습니다.

2024-05-20 03:41 UTC, cucumber99 commented on src/main/kotlin/lotto/model/Tickets.kt
> +    }
제가 작성한 코드의 경우 외부 계층에서 직접적으로 내부 상태를 변경하는 것이 아니기 때문에 위와 같은 방식도 괜찮을 것 같다고 생각하였습니다. 보통의 경우에는 후자가 클린 코드에 더 가까울 것 같네요. 한번 수정해 보겠습니다.

2024-05-20 04:36 UTC, cucumber99 commented on src/main/kotlin/lotto/model/Prize.kt
> +}
사실 아직도 코틀린에서 특정 클래스 내부에서만 사용해야 하는 상수를 선언할 때, 어떤 방식으로 상수를 다루는 것이 좋을지 감이 잡히지를 않습니다. 언어에 대한 이해도 자체가 많이 부족한 것 같아요..

2025-02-18 02:05 UTC, closed without merging